import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/layouts/Navbar/NavUser';
import Footer from '../../components/layouts/Footer';
import herologo from '../../public/herologo.png';
import Script from 'next/script';

export default function Home() {
  return (
    <>
      <Head>
        <title>Skill Test</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Navbar />
      <main>
        <div className="wrapper-home">
          <div className="container">
            <div className="row ">
              <div className="col wrap-left">
                <div className="row left-front">
                  <div className="row action-home"></div>
                  <div className="row action-home2">Company Profile</div>
                  <div className="row action-paragraph">
                    Aplikasi Perusahaan Yang Dapat Meng-input Data Dan Dapat Tersimpan Kedalam Database, Data Yang Tersimpan Di Dalam Database Dapat Dimunculkan Kepada User Aplikasi Melalui Fitur Admin.
                  </div>
                </div>
                <div className="row left-front"></div>
              </div>
              <div className="col wrap-left">
                <div className="row left-front">
                  <div className="row action-home"></div>
                  <div className="row action-home3">
                    <Image
                      src={herologo}
                      alt="logo"
                    />
                  </div>
                </div>
                <div className="row left-front"></div>
              </div>
            </div>
          </div>
        </div>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></Script>
      </main>
      <Footer />
    </>
  );
}
